# Generated by Django 5.0.6 on 2024-06-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("way_id", models.IntegerField(unique=True)),
                ("geometry_raw", models.JSONField()),
            ],
        ),
    ]
