# Generated by Django 5.0.6 on 2024-06-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="name",
        ),
    ]
