# Generated by Django 5.0.6 on 2024-06-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0002_remove_building_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="geometry_raw",
            new_name="osm_raw",
        ),
    ]
