# Generated by Django 5.0.6 on 2024-06-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0004_building_area_building_length_building_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="lat_max",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="lat_min",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="lon_max",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="lon_min",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
