# Generated by Django 5.0.7 on 2024-07-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "building",
            "0005_building_lat_max_building_lat_min_building_lon_max_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="way_id",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
