# Generated by Django 5.0.7 on 2024-07-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0006_alter_building_way_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=200)),
                ("housenumber", models.CharField(max_length=200)),
                ("postcode", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="addresses_nearby",
            field=models.ManyToManyField(to="building.address"),
        ),
    ]
