# Generated by Django 5.0.7 on 2024-07-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0007_address_building_addresses_nearby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
