# Generated by Django 5.0.7 on 2024-07-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0008_alter_address_city_alter_address_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="lat",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="lon",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="node_id",
            field=models.IntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
