# Generated by Django 5.0.7 on 2024-08-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0011_company_cattle_company_chicken_company_goat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="area",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="lat_max",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="lat_min",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="lon_max",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="lon_min",
            field=models.FloatField(db_index=True),
        ),
    ]
