# Generated by Django 5.0.7 on 2024-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0012_alter_building_area_alter_building_lat_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="lat",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="lon",
            field=models.FloatField(db_index=True),
        ),
    ]
