# Generated by Django 5.0.7 on 2024-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0013_alter_address_lat_alter_address_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="cattle",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="chicken",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="goat",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="pig",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="sheep",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
