# Generated by Django 5.0.7 on 2024-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0014_alter_company_active_alter_company_cattle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(db_index=True)),
                ("lon_min", models.FloatField(db_index=True)),
                ("lon_max", models.FloatField(db_index=True)),
                ("lat_min", models.FloatField(db_index=True)),
                ("lat_max", models.FloatField(db_index=True)),
                ("complete", models.BooleanField(db_index=True, default=False)),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
