# Generated by Django 5.0.7 on 2024-08-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0015_tile"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="duration",
            field=models.FloatField(null=True),
        ),
    ]
