# Generated by Django 5.0.7 on 2024-08-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0017_tile_building_count_tile_company_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="error",
            field=models.CharField(default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="tile",
            name="failed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
