# Generated by Django 5.0.7 on 2024-08-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0018_tile_error_tile_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="addresses_nearby_count",
            field=models.IntegerField(default=0),
        ),
    ]
