# Generated by Django 5.0.7 on 2024-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0019_building_addresses_nearby_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="addresses_nearby_count",
            field=models.IntegerField(null=True),
        ),
    ]
