# Generated by Django 5.0.7 on 2024-08-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0021_alter_address_node_id_alter_building_way_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tile",
            name="error",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
