# Generated by Django 5.0.7 on 2024-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0022_alter_tile_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.CharField(max_length=5000),
        ),
    ]
