# Generated by Django 5.0.7 on 2024-08-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0023_alter_company_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tile",
            name="error",
            field=models.CharField(blank=True, default="", max_length=10000),
        ),
    ]
