# Generated by Django 5.0.7 on 2024-08-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0024_alter_tile_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="building.company",
            ),
        ),
    ]
