# Generated by Django 5.0.7 on 2024-10-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0025_building_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="animal_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="animal_type_main",
            field=models.CharField(
                choices=[
                    ("COW", "Cow"),
                    ("PIG", "Pig"),
                    ("CHI", "Chicken"),
                    ("SHE", "Sheep"),
                    ("GOA", "Goat"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
