# Generated by Django 5.0.7 on 2024-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0026_company_animal_count_company_animal_type_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="cattle_beef",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="cattle_dairy",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="animal_type_main",
            field=models.CharField(
                choices=[
                    ("COW", "Cow"),
                    ("COD", "Cow Dairy"),
                    ("COB", "Cow Beef"),
                    ("PIG", "Pig"),
                    ("CHI", "Chicken"),
                    ("SHE", "Sheep"),
                    ("GOA", "Goat"),
                    ("COM", "Combined"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
