# Generated by Django 5.0.7 on 2024-11-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0027_company_cattle_beef_company_cattle_dairy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="other_activities",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
