# Generated by Django 5.0.7 on 2024-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0028_company_other_activities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="animal_type_main",
            field=models.CharField(
                choices=[
                    ("COD", "Cow Dairy"),
                    ("COB", "Cow Beef"),
                    ("PIG", "Pig"),
                    ("CHI", "Chicken"),
                    ("SHE", "Sheep"),
                    ("GOA", "Goat"),
                    ("COM", "Combined"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
